# Circle Packing
RESEARCH_EVAL_MAX_PARALLEL_WORKERS: 8
RESEARCH_EVAL_TIMEOUT: 1260
RESEARCH_EVAL_AVAILABLE_GPUS: [0, 1, 2, 3, 4, 5, 6, 7]
RESEARCH_SCORE_DISPLAY_PRECISION: 7

# Production config
RESEARCH_EVAL_USE_DIFF_GPU: true