# Batch Integration
RESEARCH_EVAL_MAX_PARALLEL_WORKERS: 4
RESEARCH_EVAL_TIMEOUT: 1800
RESEARCH_EVAL_USE_DIFF_GPU: false
RESEARCH_EVAL_MEMORY_LIMIT: "96g"
RESEARCH_EVAL_PYTHON_CONDA_ENV: "batch_integration"
RESEARCH_SCORE_DISPLAY_PRECISION: 4
